### ISSUE TITLE
Compatibility with ionic 3.9.x?

### ISSUE THREAD

**Issue by dayaki** [zyra/ionic2-super-tabs#348]
Am wondering if this package is compatible with ionic 3.9.2 because the compatibility table on the README shows ionic 3.5.2 - 3.6.x. I keep getting `this.nav.getActiveChildNav(...).select is not a function` error

**Comment by ihadeed** [comment]
@dayaki The latest version should work fine with 3.9.2.

**Comment by dayaki** [comment]
Been able to fix the problem, working fine now. Thanks
