### ISSUE TITLE
super tabs doesn't work on ionic 3.6.0

### ISSUE THREAD

**Issue by flyhuang** [zyra/ionic2-super-tabs#135]
Today I update ionic to 3.6.0, it breaks super-tab

Exception:
`
Uncaught (in promise): TypeError: nav.getAllChildNavs is not a function
TypeError: nav.getAllChildNavs is not a function
    at getNavByIdOrName (http://localhost:8100/build/vendor.js:22408:31)
    at getNavByIdOrName (http://localhost:8100/build/vendor.js:22410:36)
    at App.getNavByIdOrName (http://localhost:8100/build/vendor.js:22309:42)
    at getNavFromNavGroup (http://localhost:8100/build/vendor.js:66747:44)
    at hydrateSegmentsWithNav (http://localhost:8100/build/vendor.js:66715:37)
    at convertUrlToSegments (http://localhost:8100/build/vendor.js:66695:12)
    at UrlSerializer.parse (http://localhost:8100/build/vendor.js:66360:16)
    at DeepLinker.getSegmentByNavIdOrName (http://localhost:8100/build/vendor.js:25630:58)
    at SuperTabs.ngAfterViewInit (http://localhost:8100/build/vendor.js:76582:39)
    at callProviderLifecycles (http://localhost:8100/build/vendor.js:11520:18)
`

Could u help to look this issue?

Thanks very much~

**Comment by tsebvaan** [comment]
Same problem with mine

**Comment by desis123** [comment]
Having the same issue

**Comment by gimmix** [comment]
Could ionic team please stop to make this plugin break every new upgrade ? ^^

**Comment by movibe** [comment]
Having the same issue

**Comment by dkd051** [comment]
Having the same issue.
Is ionic-angular's bug?

Ionic Framework: ^3.6.0
Ionic App Scripts: 2.0.2
Angular Core: ^4.1.3
Angular Compiler CLI: 4.1.3
Node: 8.1.0
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by OmarHassan25** [comment]
Having the same issue

**Comment by danielehrhardt** [comment]
https://forum.ionicframework.com/t/ionic-3-6-0-getactivechildnavs-of-undefined/100810

**Comment by tevenFr** [comment]
Maybe it's the nav change in ionic 3.6

**Comment by danielehrhardt** [comment]
Yes i think it is

**Comment by ihadeed** [comment]
Fixed in 4.0.1 ... Sorry about the delay.

**Comment by patrickbussmann** [comment]
Sorry @ihadeed, it's not working here 😢 

![2017-08-11 01_43_32](https://user-images.githubusercontent.com/15617021/29196724-a03f65b8-7e36-11e7-9b36-73c29232e1f1.png)

I updated my project a few minutes ago by using `npm i ionic-angular@latest ionic2-super-tabs@latest --save-exact` and the result after re-run `ionic serve` is still the same.

![2017-08-11 01_45_14](https://user-images.githubusercontent.com/15617021/29196748-c7f436ba-7e36-11e7-9f5e-d8ce72409272.png)

Don't know why but currently I'm stay back on `ionic-angular 3.5.0` and `ionic2-super-tabs 3.0.2` because it's working. 😞

**Comment by wstidolph** [comment]
When I did the upgrade, I also deleted node_modules/ and package-lock.json
then did an npm-install ... I don't know if it was necessary, but "it
worked for me" :)

**Comment by danielehrhardt** [comment]
@ihadeed please reopen the issue. I created a new project and it is not working. Same Error.

**Comment by danielehrhardt** [comment]
Nothing here?? 
The problem still exists.

**Comment by flyhuang** [comment]
@danielehrhardt  it worked for me.

**Comment by ihadeed** [comment]
Closing this since it should be resolved. Make sure you are using compatible versions. I suggest you use latest version of `ionic-angular` and `ionic2-super-tabs`.

**Comment by danielehrhardt** [comment]
https://github.com/danielehrhardt/ionic2-super-tabs-example

**Comment by jasonz1987** [comment]
+1 meet the same issue 

my ionic info 

cli packages: (/Users/tuo3/git/drip-ionic3/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    ios-deploy : 1.9.1 
    ios-sim    : 4.1.1 
    Node       : v7.3.0
    npm        : 2.15.12 
    OS         : macOS Sierra
    Xcode      : Xcode 9.0 Build version 9A235 

Misc:

    backend : legacy


i'm using the lazy load page, i have three super tab father page a and three children page 

aa,bb,cc

first i push page aa  to b

```
this.app.getRootNav().push('page-b');
```
then when i push back b to a ,i got this error

```
this.app.getRootNav().push('page-a');
```

so ,any ideas?

**Comment by aleygues** [comment]
I'm facing the same problem!

**Comment by gmmx** [comment]
There is definitely a bug when we navigate with setRoot() when we use **nested** super tabs.
Is there any workaround for this problem?

**Comment by zhiyilee** [comment]
I'm facing Same Issue.

Ionic Framework: 3.7.1
Ionic App Scripts: 3.0.1
Angular Core: 4.4.4
Angular Compiler CLI: 4.4.4
Node: 6.11.4
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36 OPR/48.0.2685.32 (Edition Campaign 76)

**Comment by danielehrhardt** [comment]
Please do something here.

**Comment by zhiyilee** [comment]
Thank you for your reply.
I have fixed my self.

Awesome!!!.

**Comment by Thaars** [comment]
[This](https://github.com/ionic-team/ionic/issues/12697#issuecomment-332970073) solution worked for me for normal ion-tabs. Is it possible to add the `[tabUrlPath]` for super-tabs as well?

**Comment by acoldfox** [comment]
How did you fix it? @zhiyilee

**Comment by lincolnthree** [comment]
Confirmed this is an issue when you have super-tabs in the Navigation stack twice. E.g. When you push two pages onto the Navigation stack when both contain super-tabs.

**Comment by lincolnthree** [comment]
I believe it has to do with the wrong instance of SuperTabs receiving instructions from SuperTabsController. This occurs when I call controller.slideTo()

**Comment by lincolnthree** [comment]
Yep. Solved this by hacking the controller to return the last instance instead of the first in case it cannot find the current instance:

```
	private getInstance(id?: string): SuperTabs {
		return (!!id && this.instances[this.getInstanceIndex(id)]) || this.instances[0];
	}
```

changed to:

```
	private getInstance(id?: string): SuperTabs {
		return (!!id && this.instances[this.getInstanceIndex(id)]) || this.instances[this.instances.length - 1];
	}
```

**Comment by lincolnthree** [comment]
Seems the last instance should probably be the default in this case since that would be currently higher on the navigation stack.

**Comment by jasonz1987** [comment]
@lincolnthree i still got this error when try your code

> this.navCtrl.getActiveChildNavs(...)[0].select is not a function
> TypeError: this.navCtrl.getActiveChildNavs(...)[0].select is not a function

**Comment by lincolnthree** [comment]
Interesting. I don't get that. When does it occur? (What is the call stack or origin?)

**Comment by leonardosalles** [comment]
Still facing this issue when reload page with tabs. I just updated ionic-angular and super-tabs and the issue persists.

**Comment by armespavong** [comment]
Already found the solution but I had to change the code inside components/super-tabs.ts
Look for 
`getActiveChildNavs(): NavigationContainer[] {
    return [this._tabs[this.selectedTabIndex]];
 }`
I tried console.log for this.selectedTabIndex and it returned -1 when you switch between ionic tabs and super-tabs page, so I changed it to
`getActiveChildNavs(): NavigationContainer[] {
    if (this.selectedTabIndex < 0) {
      this.selectedTabIndex = 0;
    }
    return [this._tabs[this.selectedTabIndex]];
  }`
And now it works
