### ISSUE TITLE
this.linker.getSegmentByNavId is not a function

### ISSUE THREAD

**Issue by SteveKennedy** [zyra/ionic2-super-tabs#115]
After upgrading ionic-angular to 3.5.2 and app-scripts to 2.0.2, I get this error when running ionic serve.

TypeError: this.linker.getSegmentByNavId is not a function at SuperTabs.ngAfterViewInit (http://localhost:8100/build/vendor.js:57123:39) at callProviderLifecycles (http://localhost:8100/build/vendor.js:11799:18)

I use the @ latest of everything.  Angular, npm, etc.

I tried a full clean of node_modules, and a re-install. 

Edit - Seems like ionic-angular 3.5.2 is the culprit, as app-scripts 2.0.2 only seems ok.  Also, 3.5.1 had the same problem.  I will stay on 3.5.0 for now.
