### ISSUE TITLE
Typescript Error: find name 'NavigationContainer'

### ISSUE THREAD

**Issue by Canice-James** [zyra/ionic2-super-tabs#134]
I'm getting the following error when running ionic serve:
```

Typescript Error
Cannot find name 'NavigationContainer'.

C:/project-directory/node_modules/ionic2-super-tabs/dist/components/super-tabs.d.ts

}
  | export declare class SuperTabs implements OnInit, AfterContentInit, AfterViewInit, OnDestroy, RootNode, NavigationContainer {
  | viewCtrl: ViewController;


Typescript Error
Cannot find name 'NavigationContainer'.
C:/project-directory/node_modules/ionic2-super-tabs/dist/components/super-tabs.d.ts


slideTo(indexOrId: string \| number): void;

  | getActiveChildNavs(): NavigationContainer[];
  | addTab(tab: SuperTab): void;


```

ionic2-super-tabs: ^4.0.0
Ionic Framework: 3.5.2
Ionic Native: ^2.9.0
Ionic App Scripts: 1.3.12
Angular Core: 4.1.3
Angular Compiler CLI: 4.1.3
Node: 6.9.5

**Comment by ihadeed** [comment]
Make sure you have the correct modules installed. Your package.json might have `ionic-framework@3.5.2` but `node_modules` contains an older version. Delete `node_modules` and run `npm i` again.

**Comment by baxteruk** [comment]
I've got this as well and have updated all node_modules with not affect...
Typescript Error
Cannot find name 'NavigationContainer'.
.../project/node_modules/ionic2-super-tabs/dist/components/super-tabs.d.ts

  | export declare class SuperTabs implements OnInit, AfterContentInit, AfterViewInit, OnDestroy, RootNode, NavigationContainer {
  | viewCtrl: ViewController;

**Comment by baxteruk** [comment]
So in ionic2-super-tabs/src/components/super-tabs.ts  you're referencing `import { NavigationContainer } from 'ionic-angular/navigation/navigation-container';` however there is no folder of this name in ionic 3.7

Does this need updating to work with 3.7?

**Comment by Wmitrut** [comment]
I'm having the same issue as @baxteruk  here, the component import to

> { NavigationContainer } from 'ionic-angular/navigation/navigation-container'; 

is missing.

**Comment by fribim** [comment]
Did anyone solve this issue?

**Comment by ihadeed** [comment]
I think this would only be an issue if you're using incompatible versions. Make sure you're using latest version of `ionic-angular` and `ionic2-super-tabs`.

**Comment by fribim** [comment]
you're right. after updating everything to the latest versions it finally worked. thx!
