### ISSUE TITLE
ERROR with Ionic 3.4.2 - this._renderer.setElementStyle is not a function

### ISSUE THREAD

**Issue by gimmix** [zyra/ionic2-super-tabs#83]
Seems that the last ionic update breaks the awesome SuperTabs. It is working in Ionic 3.3.0.

## Environment
 Ionic Framework  : ionic-angular 3.4.2
 Super-tabs: 2.6.2

## Context

My page uses lazy loading.

## Error Message 
Error: Uncaught (in promise): TypeError: this._renderer.setElementStyle is not a function

console log:
TypeError: this._renderer.setElementStyle is not a function
    at SuperTab.Ion.setElementStyle (ion.js:87)
    at SuperTab.setWidth (super-tab.js:121)
    at SuperTabs.addTab (super-tabs.js:268)
    at SuperTab.ngOnInit (super-tab.js:80)

**Comment by philipgriffin** [comment]
Just got this myself when trying to use it today.

**Comment by edzillion** [comment]
This recent ionic commit has removed the keyboard stuff from `NavControllerBase` that supertabs inherits from.

52a98a101af6c29a33051d42c990e063922bc3d7#diff-9e7771d71bd3aa46debdb712a1741d86

I tried just removing the keyboard from the super call

`    function SuperTab(parent, app, config, plt, el, zone, rnd, cfr, gestureCtrl, transCtrl, errorHandler, linker, _dom, cd) {

        var _this = _super.call(this, parent, app, config, plt, el, zone, rnd, cfr, gestureCtrl, transCtrl, linker, _dom, errorHandler) || this;`

but setElementstyle is still being called on the `Keyboard` object - basically supertabs `_elementRef` is set as `Keyboard` for some reason.

`    Ion.prototype.setElementStyle = function (property, value) {
      debugger;
        this._renderer.setElementStyle(this._elementRef.nativeElement, property, value);
    };`

**Comment by edzillion** [comment]
Actually, removing all the keyboard references from super-tab.ts seemed to fix it. (really don't understand what is going on here though :/ )

I've made a pull request:

https://github.com/zyra/ionic2-super-tabs/pull/84

**Comment by ihadeed** [comment]
Just published 2.6.3 with this fix included.

**Comment by evilprince** [comment]
I am facing this issue in ionic 3.4.0 but not with 3.4.2 now. thanks!

**Comment by jonafrankbrimma** [comment]
Getting the same error on ionic 3.6.1
